-- Pedido do usuário (21/08/2026): Empréstimo entre lojas — ex: loja A
-- paga uma conta da loja B porque B estava sem saldo. A loja credora
-- (quem emprestou) desconta do Saldo dela; a loja devedora (quem pegou
-- emprestado) aumenta o Saldo dela (recebeu ajuda) e fica com uma
-- dívida em aberto, que vai sendo abatida conforme paga de volta.
create table if not exists emprestimos_entre_lojas (
  id bigint generated by default as identity primary key,
  loja_credora_id bigint not null references lojas(id), -- quem emprestou (saldo desconta)
  loja_devedora_id bigint not null references lojas(id), -- quem pegou emprestado (saldo aumenta)
  valor numeric not null,
  valor_pago numeric not null default 0,
  data date not null,
  descricao text default '',
  status text not null default 'aberto' check (status in ('aberto', 'quitado')),
  -- Pedido do usuário: quando o empréstimo nasce direto de "paguei essa
  -- Conta a Pagar com o saldo de outra loja", fica vinculado aqui —
  -- aparece junto nos relatórios, sem duplicar lançamento nenhum.
  origem_conta_pagar_id bigint references contas_pagar(id) on delete set null,
  criado_por text default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists emprestimos_entre_lojas_credora_idx on emprestimos_entre_lojas (loja_credora_id);
create index if not exists emprestimos_entre_lojas_devedora_idx on emprestimos_entre_lojas (loja_devedora_id);
create index if not exists emprestimos_entre_lojas_status_idx on emprestimos_entre_lojas (status);

-- Histórico de cada devolução parcial (ou total) de um empréstimo.
create table if not exists emprestimos_entre_lojas_pagamentos (
  id bigint generated by default as identity primary key,
  emprestimo_id bigint not null references emprestimos_entre_lojas(id) on delete cascade,
  valor numeric not null,
  data date not null,
  criado_por text default '',
  criado_em timestamptz not null default now()
);

create index if not exists emprestimos_pagamentos_emprestimo_idx on emprestimos_entre_lojas_pagamentos (emprestimo_id);
