-- Pedido do usuário (21/08/2026): Ficha Técnica, pra ter CMV real por
-- prato (não só o CMV aproximado por categoria de despesa que o sistema
-- já tinha).
--
-- IMPORTANTE: a tabela `insumos` e o controle de estoque (movimentações,
-- unidade_medida, unidade_compra, fator_conversao) JÁ EXISTIAM (tela
-- "Estoque" / CadastroInsumos.jsx) — aqui só ADICIONA a coluna de custo
-- que faltava lá, sem mexer em mais nada dessa tabela.
alter table insumos add column if not exists custo_unitario numeric not null default 0;

-- Genuinamente novo: cadastro de produtos/pratos (Ficha Técnica) e os
-- insumos que cada um usa.
create table if not exists fichas_tecnicas (
  id bigint generated by default as identity primary key,
  nome_produto text not null,
  preco_venda numeric,
  nome_item_saipos text, -- pra ligar com a venda automaticamente (fase 2)
  loja_id bigint references lojas(id),
  ativo boolean not null default true,
  observacao text default '',
  criado_por text default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists fichas_tecnicas_loja_idx on fichas_tecnicas (loja_id);
create index if not exists fichas_tecnicas_ativo_idx on fichas_tecnicas (ativo);

create table if not exists ficha_tecnica_itens (
  id bigint generated by default as identity primary key,
  ficha_tecnica_id bigint not null references fichas_tecnicas(id) on delete cascade,
  insumo_id bigint not null references insumos(id) on delete restrict,
  quantidade numeric not null,
  criado_em timestamptz not null default now()
);

create index if not exists ficha_tecnica_itens_ficha_idx on ficha_tecnica_itens (ficha_tecnica_id);
create index if not exists ficha_tecnica_itens_insumo_idx on ficha_tecnica_itens (insumo_id);
