-- Pedido do usuário (22/08/2026): retirada GENÉRICA de frente de caixa
-- (ex: "retirada de caixa -500,00", sem destino/motivo específico) não é
-- uma despesa ainda — o dinheiro só mudou de lugar (saiu do caixa,
-- guardado em algum lugar pra gasto futuro). Vira um "fundo" à parte,
-- sem descontar o Saldo na hora. Só quando for de fato gasto numa
-- compra é que vira despesa de verdade (marcando "pago com esse fundo"),
-- e AÍ sim desconta o Saldo.
create table if not exists fundo_retiradas_caixa (
  id bigint generated by default as identity primary key,
  loja_id bigint not null references lojas(id),
  valor numeric not null,
  valor_usado numeric not null default 0,
  data date not null,
  descricao text default '',
  status text not null default 'aberto' check (status in ('aberto', 'esgotado')),
  criado_por text default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists fundo_retiradas_caixa_loja_idx on fundo_retiradas_caixa (loja_id);
create index if not exists fundo_retiradas_caixa_status_idx on fundo_retiradas_caixa (status);

-- Liga uma despesa "paga com o fundo" ao fundo de onde saiu o dinheiro —
-- pra dar pra ver depois em que foi gasto e não deixar usar o mesmo
-- dinheiro duas vezes.
alter table lancamentos add column if not exists fundo_retirada_id bigint references fundo_retiradas_caixa(id) on delete set null;
