-- Pedido do usuário (23/08/2026): insumo "feito na casa" (ex: maionese —
-- não é comprada pronta, é preparada com outros insumos) — o custo
-- unitário dele passa a poder ser CALCULADO a partir de uma receita
-- própria (outros insumos + quantidade de cada + quanto a receita rende),
-- em vez de digitado direto. Mesma ideia da Ficha Técnica dos produtos
-- vendidos, só que aplicada a um INSUMO em vez de um prato.
alter table insumos add column if not exists rendimento numeric;

create table if not exists insumo_receita_itens (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references insumos(id) on delete cascade,
  insumo_ingrediente_id bigint not null references insumos(id) on delete restrict,
  quantidade numeric not null,
  criado_em timestamptz not null default now()
);

create index if not exists insumo_receita_itens_insumo_idx on insumo_receita_itens (insumo_id);
create index if not exists insumo_receita_itens_ingrediente_idx on insumo_receita_itens (insumo_ingrediente_id);
